[
    {
        "alertType" : "bookingMessage",
        "notifyBy" :  "email",
        "active" : true
    },

    {
        "alertType" : "shipmentMessage",
        "notifyBy" :  "email",
        "active" : true
    },

    {
        "alertType" : "shipmentEtaChanged",
        "notifyBy" :  "email",
        "active" : true
    },

    {
        "alertType" : "shipmentEtdChanged",
        "notifyBy" :  "email",
        "active" : true
    }


]