[
    {
        "alertType" : "bookingMessage",
        "notifyBy" :  "email",
        "active" : true
    },

    {
        "alertType" : "shipmentMessage",
        "notifyBy" :  "email",
        "active" : true
    },

    {
        "alertType" : "bookingalerttest",
        "notifyBy" :  "email",
        "active" : true
    },

    {
        "alertType" : "shipmenttest",
        "notifyBy" :  "email",
        "active" : true
    }

]