{
    "first": {

      "value" : "Hello{{person.userName}}，swivel 360 here",
      "color" : "#173177"

    },

    "keyword1": {

      "value" : "{{title}}",
      "color" : "#173177"

    },

    "keyword2": {

      "value" : "booking message : {{message}}",
      "color" : "#173177"

    },

    "remark": {

      "value" : "click {{url}} to check it",
      "color" : "#173177"

    }

  }
  