import { JqlDefinition } from 'modules/report/interface'


const documentFileNameList = [
  'Freight Invoice',
  'MBL',
  'HBL Original',
  'HBL Telex released',
  'Commercial Invoice',
  'Packing List',
  'Quotation',
]

export default {
  jqls: [
    {
      type: 'callDataService',
      dataServiceQuery: ['booking', 'booking']
    }
  ],
  columns: [
    { key: 'createdAt' },
    { key: 'updatedAt' },
    { key: 'id' },
    { key: 'shipId' },
   { key: 'shipmentId' },
    { key: 'houseNo' },
    { key: 'masterNo' },
     { key: 'poNo' },
    { key: 'bookingNo' },
    { key: 'moduleType' }, //need this
   { key: 'boundType' },
    { key: 'service' },
    { key: 'incoTerms' },
    { key: 'freightTerms' },
    { key: 'otherTerms' },
    { key: 'finalVesselName' },
    { key: 'finalVoyageFlightNumber' },
    { key: 'commodity' },
    { key: 'polHScode' },
    { key: 'placeOfReceiptName' },
    { key: 'portOfLoadingName' },
    { key: 'portOfDischargeName' },
    { key: 'placeOfDeliveryName' },
    { key: 'finalDestinationName' },
    { key: 'carrierName' },
    { key: 'cargoReadyDateEstimated' },
    { key: 'cargoReadyDateActual' },
    { key: 'cargoReadyDateRemark' },
    { key: 'shipperInstructionSubmitDateEstimated' },
    { key: 'shipperInstructionSubmitDateActual' },
    { key: 'shipperInstructionSubmitDateRemark' },
    { key: 'bookingSubmitDateEstimated' },
    { key: 'bookingSubmitDateActual' },
    { key: 'bookingSubmitDateRemark' },
    { key: 'cYCutOffDateEstimated' },
    { key: 'cYCutOffDateActual' },
    { key: 'cYCutOffDateRemark' },
    { key: 'customClearanceLoadingPortDateEstimated' },
    { key: 'customClearanceLoadingPortDateActual' },
    { key: 'customClearanceLoadingPortDateRemark' },
    { key: 'departureDateEstimated' },
    { key: 'departureDateActual' },
    { key: 'departureDateRemark' },
    { key: 'arrivalDateEstimated' },
    { key: 'arrivalDateActual' },
    { key: 'arrivalDateRemark' },
    { key: 'customClearanceDestinationPortDateEstimated' },
    { key: 'customClearanceDestinationPortDateActual' },
    { key: 'customClearanceDestinationPortDateRemark' },
    { key: 'finalDoorDeliveryDateEstimated' },
    { key: 'finalDoorDeliveryDateActual' },
    { key: 'finalDoorDeliveryDateRemark' },
    { key: 'createdUserEmail' },
    { key: 'updatedUserEmail' },
    { key: 'shipperPartyCode' },
    { key: 'shipperPartyName' },
    { key: 'shipperPartyContactEmail' },
    { key: 'shipperPartyContactName' },
    { key: 'consigneePartyCode' },
    { key: 'consigneePartyName' },
    { key: 'consigneePartyContactEmail' },
    { key: 'consigneePartyContactName' },
    { key: 'forwarderPartyName' },
    { key: 'forwarderPartyCode' },
    { key: 'forwarderPartyContactEmail' },
    { key: 'forwarderPartyContactName' },
    { key: 'notifyPartyPartyCode' },
    { key: 'notifyPartyPartyName' },
    { key: 'notifyPartyPartyContactEmail' },
    { key: 'notifyPartyPartyContactName' },
    { key: 'agentPartyCode' },
    { key: 'agentPartyName' },
    { key: 'agentPartyContactEmail' },
    { key: 'agentPartyContactName' },
    { key: 'containerTypeCode' },
    { key: 'allSoNo' },
    { key: 'allContainerNo' },
    { key: 'totalQuantity' },
    { key: 'totalQuantityUnit' },
    { key: 'lastStatusCodeOrDescription' },
    { key: 'lastStatusDate' },
    { key: 'lastStatusWidget' },
    ...documentFileNameList.map(documentFileName => {

      return { key: `haveDocument_${documentFileName}` }

    })
  ],
} as JqlDefinition
